### ISSUE TITLE
Nu iti recomand sa expui la internet un nod http (nu https) si mai ales, cel mai important, sa nu introduci parola ta privata in acel nod.

### ISSUE THREAD

**Issue by dan-mih** [CoopNetwork/GMD-blockchain#19]
Nodul a fost transformat in nod privat (nu mai este accesibil din internet).

Mai am  trei intrebari:

1. se poate face forging pe nodul privat, daca wallet-ul a fost dat in leasing pe un alt nod?
2. care sunt avantajele financiare ale detinerii unui nod (public, sau privat)?
3. puteti sa ma ajutati cu documentatie despre procesul de certificare a unui nod ?(KYC etc)

_Originally posted by @zupermann in https://github.com/CoopNetwork/GMD-blockchain/discussions/14#discussioncomment-1540421_

**Comment by zupermann** [comment]
Salutare,

Pot raspunde doar la intrebari tehnice aici. Pentru aspectele financiare sau de certificare te rog sa folosesti canalele de Telegram, acolo vei primi mai repde un raspuns.

Pot raspunde doar la prima intrebare si o mica observatie la intrebarea 2.
1. Nu poti face tu forging cu monedele pe care le-ai dat in leasing. Doar portofelul care le-a primit poate face forging.
2. Nu pot raspunde despre partea financiara, dar avantajul sa ai nodul tau este securitatea sporita. Ai control asupra propriului portofel doar de pe masina ta si nu iti expui serverul la alte servere care nu sunt in controlul tau. 
Deasemenea un numar mare de noduri distribuite contribuie la descentralizarea si securitatea retelei per total.
