### ISSUE TITLE
TotalSupply and MaxSupply endpoints

### ISSUE THREAD

**Issue by florintimbuc** [CoopNetwork/GMD-blockchain#39]
It seems that The Coop Network should be more transparent regarding the transmission of TotalSupply and MaxSupply for a live CirculatingSupply calculation made by CoinMarketCap (https://support.coinmarketcap.com/hc/en-us/articles/360043396252-Supply-Circulating-Total-Max-).

From their documentation:
> Total Supply = # of coins in existence right now (minus any coins that have been verifiably burned).
> Max Supply = maximum # of coins that will ever exist in the lifetime of the cryptocurrency.

What we need to provide:
> API endpoint that displays ONLY 'Total Supply' as a numerical value (e.g. http://chainz.cryptoid.info/grs/api.dws?q=totalcoins)

Plus, I think a MaxSupply endpoint would be useful for further scenarios or use cases.

**Comment by zupermann** [comment]
Fixed with PR #40

**Comment by zupermann** [comment]
@florintimbuc you can test the new endpoints on https://node.thecoopnetwork.io:8443/

https://node.thecoopnetwork.io:8443/nxt?=%2Fnxt&requestType=getMaxSupply
https://node.thecoopnetwork.io:8443/nxt?=%2Fnxt&requestType=getTotalSupply
