### ISSUE TITLE
Count of transactions and accounts endpoints

### ISSUE THREAD

**Issue by florintimbuc** [CoopNetwork/GMD-blockchain#41]
We need to extend our API for explorer and third-party integrations with endpoints for:
- total number of transactions from genesis
- total number of accounts

**Comment by zupermann** [comment]
Created 2 new endpoints that return a number (not a json as usual) called countAccounts and countTransactions. They take no mandatory parameters.

**Comment by zupermann** [comment]
![image](https://user-images.githubusercontent.com/4907747/189306285-1983e810-b77e-45ff-acde-5594124173cd.png)

![image](https://user-images.githubusercontent.com/4907747/189306382-ca6dd397-daed-4f77-94ad-025b289fe861.png)

**Comment by zupermann** [comment]
New endpoints were deployed. You can test them here:
https://node.thecoopnetwork.io:8443/test
