### ISSUE TITLE
getAccountsBulk with effective Balance

### ISSUE THREAD

**Issue by florintimbuc** [CoopNetwork/GMD-blockchain#42]
To enhance the Accounts list view from explorer with both effective and unconfirmed balances, we need to extend the API method and return the effective balances too.

**Comment by zupermann** [comment]
If effective balance is needed, please set includeEffectiveBalance to true.
![image](https://user-images.githubusercontent.com/4907747/189301847-7badf0b1-38e7-49fc-a963-022f3afaacb2.png)

**Comment by zupermann** [comment]
New endpoints were deployed. You can test them here:
https://node.thecoopnetwork.io:8443/test
